version: 2.1
orbs:
  foc-orb-test: sreejithfocaloid/foc-orb-test@0.0.13

jobs:
  scan:
    docker:
      - image: cimg/base:<< pipeline.parameters.cimg-tag >>
    
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - foc-orb-test/xray:
          imageName: << pipeline.parameters.image-name >>
          cimgTag: << pipeline.parameters.cimg-tag >>
      - store_artifacts:
          path: /tmp/artifact-xray
          destination: xray-json
      - foc-orb-test/vscan:
          imageName: << pipeline.parameters.image-name >>
          cimgTag: << pipeline.parameters.cimg-tag >>
      - store_artifacts:
          path: /tmp/artifact-vscan
          destination: vscan-json
workflows:
  engine-execution:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - scan