version: 2.1

orbs:
  foc-orb-test: sreejithfocaloid/foc-orb-test@0.0.7

jobs:
  scan:
    docker:
      - image: cimg/base:current
    parameters:
      image-name:
        description: Image to be scanned.
        type: string
        default: nginx
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - foc-orb-test/xray:
          imageName: << parameters.image-name >>
      - store_artifacts:
          path: /tmp/artifact-xray
          destination: xray-json
      - foc-orb-test/vscan:
          imageName: << parameters.image-name >>
      - store_artifacts:
          path: /tmp/artifact-vscan
          destination: vscan-json
workflows:
  engine-execution:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - scan